config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get '/home', to: 'pages#home'
  
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  
end

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Track-it App</h1>
  
  <h2>This is the home page for Track-it App simple and efficient way to manage your requests</h2>
  
  <%= link_to "Sign up Now", register_path, class: "btn btn-lg btn-success" %>
</div>

<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">
      View Track-it as Guest user
    </h3>
    <h2 class="left">Browse and View Track-it as a guest and sign up later</h2>
    <p><%= link_to "Browse Request Listings", recipes_path, class: "btn btn-warning btn-small" %></p>
  </div>
   <div class="col-lg-4">
    <h3 class="midrow">
      Sign in to your account</h3>
    <h2 class="left">Add/Update your records, create reviews, like/dislike requests!</h2>
    <p><%= link_to "Login in to your account", login_path, class: "btn btn-warning btn-small" %></p>
  </div>
   <div class="col-lg-4">
    <h3 class="midrow">
      View Track-It as Guest user</h3>
    <h2 class="left">Browse and View Track-it as a guest and sign up later</h2>
    <p><%= link_to "Browse Request Listings", "", class: "btn btn-warning btn-small" %></p>
  </div>
</div>